{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-host-shared",
    "version": "0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "7wc53zwylzghhj6na2g4ac5nsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "native-host-shared-0.4-SNAPSHOT.jar",
          "url": "native-host-shared-0.4-SNAPSHOT.jar",
          "size": 168919,
          "sha512": "3990e981db682f3feb774e3a8fe05bde7594711ca21d518de4b16743e3b1645d867d586f4854f4895fa1a640b0ae2bc9af56fdb075bcba8e89c92a07dbb6381b",
          "sha256": "7932a19740c4d6ffca68951682219da07212482c78b38ce14587efcd55c5c522",
          "sha1": "410a5dad051e6af7e809c3de9fd01c95f63cf979",
          "md5": "cd848c7484bbb5310ad78fc0e4e1d44d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "native-host-shared-0.4-SNAPSHOT.jar",
          "url": "native-host-shared-0.4-SNAPSHOT.jar",
          "size": 168919,
          "sha512": "3990e981db682f3feb774e3a8fe05bde7594711ca21d518de4b16743e3b1645d867d586f4854f4895fa1a640b0ae2bc9af56fdb075bcba8e89c92a07dbb6381b",
          "sha256": "7932a19740c4d6ffca68951682219da07212482c78b38ce14587efcd55c5c522",
          "sha1": "410a5dad051e6af7e809c3de9fd01c95f63cf979",
          "md5": "cd848c7484bbb5310ad78fc0e4e1d44d"
        }
      ]
    }
  ]
}
